import 'dart:io';
import 'package:auto_route/auto_route.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:hwzn_base/general/constants/modals/LoadingDialog.dart';
import 'package:hwzn_base/general/helper/validator/Validator.dart';
import 'package:hwzn_base/general/models/dropdown_model/dropdown_model.dart';
import 'package:hwzn_base/general/models/toJson/RegisterCenterModel.dart';
import 'package:hwzn_base/general/models/toJson/RegisterDoctorModel.dart';
import 'package:hwzn_base/general/screens/register/widgets/RegisterWidgetsImports.dart';
import 'package:hwzn_base/general/widgets/AuthScaffold.dart';
import 'package:hwzn_base/general/widgets/DefaultButton.dart';
import 'package:hwzn_base/provider/screens/prov_register/widgets/ProvRegisterWidgetsImports.dart';
import 'package:intl_phone_number_input/intl_phone_number_input.dart';
import '../../../general/constants/MyColors.dart';
import '../../../general/constants/custom_ drop_down/CustomDropDown.dart';
import '../../../general/helper/configration/CustomButtonAnimation.dart';
import '../../../general/helper/helper_methods/HelperMethods.dart';
import '../../../general/packages/generic_bloc/generic_cubit.dart';
import '../../../general/resources/GeneralRepoImports.dart';
import '../../../general/utilities/utils_functions/LoadingDialog.dart';
import '../../../general/widgets/LoadingButton.dart';

part 'ProvRegister.dart';
part 'ProvRegisterData.dart';