import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hwzn_base/general/utilities/routers/RouterImports.gr.dart';
import 'package:hwzn_base/user/models/doctor_model.dart';
import 'package:hwzn_base/user/screens/session/SessionImports.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:stop_watch_timer/stop_watch_timer.dart';
import 'dart:math' as math;
import '../../../../general/constants/MyColors.dart';
import '../../../../general/packages/generic_bloc/generic_cubit.dart';
import '../../../../general/widgets/CachedImage.dart';
import '../../../../general/widgets/DefaultButton.dart';
import '../../../../general/widgets/MyText.dart';
import '../../../../res.dart';
import '../../add_reservation/widgets/AddReservationWidgetsImports.dart';

part 'BuildSessionHeader.dart';
part 'BuildSessionTimer.dart';
part 'BuildSessionDoctor.dart';
part 'BuildSessionPet.dart';
part 'BuildSessionInvite.dart';
part 'BuildCancelBottomSheet.dart';
part 'BuildCancelDetBottomSheet.dart';
part 'BuildChangeTimeBottomSheet.dart';