import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_google_places/flutter_google_places.dart';
import 'package:google_api_headers/google_api_headers.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:google_maps_webservice/places.dart';
import 'package:location/location.dart';
import '../../../res.dart';
import '../../blocks/lang_cubit/lang_cubit.dart';
import '../../constants/MyColors.dart';
import '../../constants/modals/LoadingDialog.dart';
import '../../models/LocationModel.dart';
import '../../packages/generic_bloc/generic_cubit.dart';
import '../../utilities/utils_functions/UtilsImports.dart';
import '../../widgets/MyText.dart';
import 'location_cubit/location_cubit.dart';
import 'widgets/LocationWidgetsImports.dart';

part 'LocationAddress.dart';
part 'LocationAddressData.dart';
