import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hwzn_base/general/constants/MyColors.dart';
import 'package:hwzn_base/general/packages/input_fields/GenericTextField.dart';
import 'package:hwzn_base/general/utilities/routers/RouterImports.gr.dart';
import 'package:hwzn_base/general/widgets/CachedImage.dart';
import 'package:hwzn_base/general/widgets/MyText.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import '../../../../../../res.dart';
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
import 'dart:math' as math;
import 'package:hwzn_base/general/helper/validator/Validator.dart';

part 'BuildMainAppBar.dart';
part 'BuildMainSearch.dart';
part 'BuildMainImage.dart';
part 'BuildSpecializationSection.dart';
part 'BuildDoctorsSection.dart';
part 'BuildSpecItem.dart';
part 'BuildDoctorItem.dart';