/// Generated by AssetsRefGenerator on 2022/12/25
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoWhite = "assets/images/logoWhite.png";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String onboardingOne = "assets/images/onboardingOne.jpeg";
  static const String onboardingThree = "assets/images/onboardingThree.jpeg";
  static const String onboardingTwo = "assets/images/onboardingTwo.jpeg";
  static const String password = "assets/images/password.svg";
  static const String twitter = "assets/images/twitter.png";
  static const String upload = "assets/images/upload.png";
  static const String sliderImage = "assets/images/sliderImage.png";
  static const String forgetPass = "assets/images/forgetPass.png";
  static const String verification = "assets/images/verification.png";
  static const String bottomShape = "assets/images/bottomShape.png";
  static const String chat = "assets/images/chat.png";
  static const String homeLogoWhite = "assets/images/homeLogoWhite.png";
  static const String filter = "assets/images/filter.png";
}
